### ISSUE TITLE
Add CRUD support for the generic assets

### ISSUE THREAD

**Issue by lasconic** [lasconic/finary#1]
* Get the "others" assets
Via `views`, like the web UI
```
GET https://api.finary.com/users/me/views/other_assets?period=all
```
Via the CRUD endpoint ?
```
GET https://api.finary.com/users/me/generic_assets
```

* Get  the "others" assets categories
```
GET https://api.finary.com/generic_asset_categories/autocomplete 
```

* Create a generic asset
```
POST  https://api.finary.com/users/me/generic_assets
{
  "name": "test",
  "category": "real_estate_crowdfunding",
  "quantity": "1",
  "buying_price": "1",
  "current_price": "1"
}
```

* Update a generic asset
```
PUT https://api.finary.com/users/me/generic_assets/<asset_id>
{
  "name": "test",
  "category": "g3f",
  "quantity": "2",
  "buying_price": "2",
  "current_price": "2",
  "id": <asset_id>
}
```

* Delete a generic asset
```
DELETE https://api.finary.com/users/me/generic_assets/24862
```
return HTTP code 204 if successful  (and no json)

**Comment by cpavot** [comment]
Thanks! I have started using generic asset commands and they work fine. FYI, I have integrated them in a (quick-and-dirty) script to read my emails, extract the latest account values from account summary emails and update my finary assets in an automated way.
