### ISSUE TITLE
All 'annual_yield' are null

### ISSUE THREAD

**Issue by nmathey** [lasconic/finary#54]
Did it even work before or Finary change is API on this reported data?
Reported null on all modules results: Holdings, investments, portfolio, etc.

**Comment by lasconic** [comment]
I believe annual_yield is null for quite some time now but it's somehow beyond the score of this project to check the output. I started another project to document the API and detect the changes at : https://github.com/lasconic/openapi-finary
but I didn't work on it for some time. Help welcome :)
