### ISSUE TITLE
Crowdlendings

### ISSUE THREAD

**Issue by sebfar9172** [lasconic/finary#73]
Bonjour
Serait-il possible de récupérer les données de la section Crowdlending ?

**Comment by lasconic** [comment]
On les a dans les holdings_accounts je pense ? Tu veux quelque chose en particulier qui ne se trouve pas là ?

**Comment by sebfar9172** [comment]
Oui je trouvé ensuite merci

**Comment by lasconic** [comment]
Je viens de voir sur finalynx ;) good job !

**Comment by lasconic** [comment]
J'ai ajouté des calls directs pour récupérer seulement le crowdlending

**Comment by sebfar9172** [comment]
Le soucis c'est que les comptes de crowdlending qui sont synchronisés ne sont pas tagues crowdlendings

**Comment by lasconic** [comment]
Et si tu appelles le nouveau endpoint ajouté ici : https://github.com/lasconic/finary/commit/7f537c9de80dbd55376a5a74f6900f50c2aa53a1 ? tu as tout ?

**Comment by lasconic** [comment]
Voir https://github.com/MadeInPierre/finalynx/issues/71

**Comment by sebfar9172** [comment]
> Et si tu appelles le nouveau endpoint ajouté ici : [7f537c9](https://github.com/lasconic/finary/commit/7f537c9de80dbd55376a5a74f6900f50c2aa53a1) ? tu as tout ?

Hello je n'arrive pas à mettre à jour la version pour avoir ce nouveau endpoint

**Comment by sebfar9172** [comment]
C'est bon avec endpoint indiqué merci
